<?php
// catalog.php — the REAL product catalog, extracted from your index.html
// on 2026-07-05. This is now the ONLY place
// prices exist. Whatever price/duration a request sends is ignored —
// every purchase endpoint looks the real price up from here by `sku`.
//
// Found while extracting: two rows in your HTML ("HG CHEATS NON ROOT" and
// "HG CHEATS ROOT") both use pid 65. That made pid+duration ambiguous for
// 4 items, so this catalog keys everything by a clean, unique `sku`
// instead (sku_1..sku_79) — pid is kept only as reference metadata.

const CATALOG = [
  'sku_1' => ['pid' => '91', 'row' => 'DRIP CLINT PROXY', 'name' => 'DRIP PROXY 1 DAY', 'duration' => '1 DaYs', 'price' => 120, 'external' => true],
  'sku_2' => ['pid' => '91', 'row' => 'DRIP CLINT PROXY', 'name' => 'DRIP PROXY 3 DAY', 'duration' => '3 DaYs', 'price' => 220, 'external' => true],
  'sku_3' => ['pid' => '91', 'row' => 'DRIP CLINT PROXY', 'name' => 'DRIP PROXY 7 DAY', 'duration' => '7 DaYs', 'price' => 450, 'external' => true],
  'sku_4' => ['pid' => '91', 'row' => 'DRIP CLINT PROXY', 'name' => 'DRIP PROXY 15 DAY', 'duration' => '15 DaYs', 'price' => 650, 'external' => true],
  'sku_5' => ['pid' => '91', 'row' => 'DRIP CLINT PROXY', 'name' => 'DRIP PROXY 30 DAY', 'duration' => '30 DaYs', 'price' => 920, 'external' => true],
  'sku_6' => ['pid' => '62', 'row' => 'DRIP CLINT GLOBAL', 'name' => 'DRIP 1 DAY', 'duration' => '1 DaYS NONROOT', 'price' => 120, 'external' => true],
  'sku_7' => ['pid' => '62', 'row' => 'DRIP CLINT GLOBAL', 'name' => 'DRIP 3 DAY', 'duration' => '3 DaYS NONROOT', 'price' => 220, 'external' => true],
  'sku_8' => ['pid' => '62', 'row' => 'DRIP CLINT GLOBAL', 'name' => 'DRIP 7 DAY', 'duration' => '7 DaYS NONROOT', 'price' => 450, 'external' => true],
  'sku_9' => ['pid' => '62', 'row' => 'DRIP CLINT GLOBAL', 'name' => 'DRIP 15 DAY', 'duration' => '15 DaYS NONROOT', 'price' => 650, 'external' => true],
  'sku_10' => ['pid' => '62', 'row' => 'DRIP CLINT GLOBAL', 'name' => 'DRIP 30 DAY', 'duration' => '30 DaYS NONROOT', 'price' => 920, 'external' => true],
  'sku_11' => ['pid' => '63', 'row' => 'DRIP CLINT ROOT', 'name' => 'DRIP ROOT 1 DAY', 'duration' => '1 DaYs', 'price' => 170, 'external' => true],
  'sku_12' => ['pid' => '63', 'row' => 'DRIP CLINT ROOT', 'name' => 'DRIP ROOT 7 DAY', 'duration' => '7 DaYs', 'price' => 550, 'external' => true],
  'sku_13' => ['pid' => '63', 'row' => 'DRIP CLINT ROOT', 'name' => 'DRIP ROOT 30 DAY', 'duration' => '30 DaYS ROOT', 'price' => 1080, 'external' => true],
  'sku_14' => ['pid' => '44', 'row' => 'DRIP CLINT PC', 'name' => 'DRIP PC 1 DAY', 'duration' => '1 DaYS PC AIMKILL', 'price' => 200, 'external' => true],
  'sku_15' => ['pid' => '44', 'row' => 'DRIP CLINT PC', 'name' => 'DRIP PC 7 DAY', 'duration' => '7 DaYS PC AIMKILL', 'price' => 650, 'external' => true],
  'sku_16' => ['pid' => '44', 'row' => 'DRIP CLINT PC', 'name' => 'DRIP PC 15 DAY', 'duration' => '15 DaYS PC AIMKILL', 'price' => 900, 'external' => true],
  'sku_17' => ['pid' => '44', 'row' => 'DRIP CLINT PC', 'name' => 'DRIP PC 30 DAY', 'duration' => '30 DaYS PC AIMKILL', 'price' => 1450, 'external' => true],
  'sku_18' => ['pid' => '65', 'row' => 'HG CHEATS NON ROOT', 'name' => 'HG CHEATS 1 DAY', 'duration' => '1 DaYs Root + Nonroot', 'price' => 130, 'external' => true],
  'sku_19' => ['pid' => '65', 'row' => 'HG CHEATS NON ROOT', 'name' => 'HG CHEATS 7 DAY', 'duration' => '7 DaYs Root+Nonroot', 'price' => 350, 'external' => true],
  'sku_20' => ['pid' => '65', 'row' => 'HG CHEATS NON ROOT', 'name' => 'HG CHEATS 10 DAY', 'duration' => '10 DaYs Root+Nonroot', 'price' => 450, 'external' => true],
  'sku_21' => ['pid' => '65', 'row' => 'HG CHEATS NON ROOT', 'name' => 'HG CHEATS 30 DAY', 'duration' => '30 DaYs Root+Nonroot', 'price' => 750, 'external' => true],
  'sku_22' => ['pid' => '123', 'row' => 'HG CHEATS PROXY NON ROOT', 'name' => 'HG CHEATS PROXY 1 DAY', 'duration' => '1 DaYs', 'price' => 130, 'external' => true],
  'sku_23' => ['pid' => '123', 'row' => 'HG CHEATS PROXY NON ROOT', 'name' => 'HG CHEATS PROXY 7 DAY', 'duration' => '7 DaYs', 'price' => 350, 'external' => true],
  'sku_24' => ['pid' => '123', 'row' => 'HG CHEATS PROXY NON ROOT', 'name' => 'HG CHEATS PROXY 10 DAY', 'duration' => '10 DaYs', 'price' => 450, 'external' => true],
  'sku_25' => ['pid' => '123', 'row' => 'HG CHEATS PROXY NON ROOT', 'name' => 'HG CHEATS PROXY 30 DAY', 'duration' => '30 DaYs', 'price' => 750, 'external' => true],
  'sku_26' => ['pid' => '65', 'row' => 'HG CHEATS ROOT', 'name' => 'HG CHEATS ROOT 1 DAY', 'duration' => '1 DaYs Root + Nonroot', 'price' => 130, 'external' => true],
  'sku_27' => ['pid' => '65', 'row' => 'HG CHEATS ROOT', 'name' => 'HG CHEATS ROOT 7 DAY', 'duration' => '7 DaYs Root+Nonroot', 'price' => 350, 'external' => true],
  'sku_28' => ['pid' => '65', 'row' => 'HG CHEATS ROOT', 'name' => 'HG CHEATS ROOT 10 DAY', 'duration' => '10 DaYs Root+Nonroot', 'price' => 450, 'external' => true],
  'sku_29' => ['pid' => '65', 'row' => 'HG CHEATS ROOT', 'name' => 'HG CHEATS ROOT 30 DAY', 'duration' => '30 DaYs Root+Nonroot', 'price' => 750, 'external' => true],
  'sku_30' => ['pid' => '54', 'row' => 'PATO TEAM', 'name' => 'PATO MIX 3 DAY', 'duration' => '3 DaYs All Colours Mix', 'price' => 550, 'external' => true],
  'sku_31' => ['pid' => '54', 'row' => 'PATO TEAM', 'name' => 'PATO MIX 7 DAY', 'duration' => '7 DaYs All Colours Mix', 'price' => 850, 'external' => true],
  'sku_32' => ['pid' => '54', 'row' => 'PATO TEAM', 'name' => 'PATO MIX 15 DAY', 'duration' => '15 DaYs All Colours Mix', 'price' => 1250, 'external' => true],
  'sku_33' => ['pid' => '54', 'row' => 'PATO TEAM', 'name' => 'PATO MIX 30 DAY', 'duration' => '30 DaYs All Colours Mix', 'price' => 1550, 'external' => true],
  'sku_34' => ['pid' => '58', 'row' => 'IOS FLUORITE', 'name' => 'Gbox Clarification', 'duration' => 'Gbox Clarification', 'price' => 1500, 'external' => true],
  'sku_35' => ['pid' => '58', 'row' => 'IOS FLUORITE', 'name' => 'FLUORITE 1 DAY', 'duration' => '1 DAYs FluoRite FF', 'price' => 550, 'external' => true],
  'sku_36' => ['pid' => '58', 'row' => 'IOS FLUORITE', 'name' => 'FLUORITE 7 DAY', 'duration' => '7 DAYs FluoRite FF', 'price' => 1550, 'external' => true],
  'sku_37' => ['pid' => '58', 'row' => 'IOS FLUORITE', 'name' => 'FLUORITE 30 DAY', 'duration' => '30 DAYs FluoRite FF', 'price' => 3200, 'external' => true],
  'sku_38' => ['pid' => '48', 'row' => 'PRIME HOOK', 'name' => 'PRIME 1 DAY', 'duration' => '1 Days Nonroot', 'price' => 100, 'external' => true],
  'sku_39' => ['pid' => '48', 'row' => 'PRIME HOOK', 'name' => 'PRIME 3 DAY', 'duration' => '3 Days Nonroot', 'price' => 160, 'external' => true],
  'sku_40' => ['pid' => '48', 'row' => 'PRIME HOOK', 'name' => 'PRIME 7 DAY', 'duration' => '7 Days NonRoot', 'price' => 300, 'external' => true],
  'sku_41' => ['pid' => '48', 'row' => 'PRIME HOOK', 'name' => 'PRIME 10 DAY', 'duration' => '10 Days Nonroot', 'price' => 500, 'external' => true],
  'sku_42' => ['pid' => '64', 'row' => 'HAXX-CKER PRO ANDROID ROOT', 'name' => 'HAXX-CKER PRO ROOT DAY', 'duration' => '10 DaYs', 'price' => 1500, 'external' => true],
  'sku_43' => ['pid' => '67', 'row' => 'BR MOD ROOT', 'name' => 'BR 1 DAY', 'duration' => '1 DaYs', 'price' => 150, 'external' => true],
  'sku_44' => ['pid' => '67', 'row' => 'BR MOD ROOT', 'name' => 'BR 7 DAY', 'duration' => '7 DaYs', 'price' => 450, 'external' => true],
  'sku_45' => ['pid' => '67', 'row' => 'BR MOD ROOT', 'name' => 'BR 15 DAY', 'duration' => '15 DaYs', 'price' => 750, 'external' => true],
  'sku_46' => ['pid' => '67', 'row' => 'BR MOD ROOT', 'name' => 'BR MOD 30 DAY', 'duration' => '30 DaYs', 'price' => 1250, 'external' => true],
  'sku_47' => ['pid' => '49', 'row' => 'BR MOD PC', 'name' => 'BR PC 1 DAY', 'duration' => '1 Day Pc Aim Silent', 'price' => 180, 'external' => true],
  'sku_48' => ['pid' => '49', 'row' => 'BR MOD PC', 'name' => 'BR PC 10 DAY', 'duration' => '10 Days Pc Aim Silent', 'price' => 650, 'external' => true],
  'sku_49' => ['pid' => '49', 'row' => 'BR MOD PC', 'name' => 'BR PC 30 DAY', 'duration' => '30 Days Pc Aim Silent', 'price' => 1250, 'external' => true],
  'sku_50' => ['pid' => '49', 'row' => 'BR MOD PC', 'name' => 'BR PC BYPASS 1 DAY', 'duration' => '1 Day Pc Bypass + Silent', 'price' => 250, 'external' => true],
  'sku_51' => ['pid' => '49', 'row' => 'BR MOD PC', 'name' => 'BR PC BYPASS 10 DAY', 'duration' => '10 Days Pc Bypass + Silent', 'price' => 750, 'external' => true],
  'sku_52' => ['pid' => '49', 'row' => 'BR MOD PC', 'name' => 'BR PC BYPASS 30 DAY', 'duration' => '30 Days Pc Bypass + Silent', 'price' => 1450, 'external' => true],
  'sku_53' => ['pid' => '66', 'row' => 'XYZ ROOT', 'name' => 'XYZ 3 DAY', 'duration' => '3 Days', 'price' => 140, 'external' => true],
  'sku_54' => ['pid' => '66', 'row' => 'XYZ ROOT', 'name' => 'XYZ 7 DAY', 'duration' => '7 Days', 'price' => 240, 'external' => true],
  'sku_55' => ['pid' => '66', 'row' => 'XYZ ROOT', 'name' => 'XYZ 15 DAY', 'duration' => '15 Days', 'price' => 450, 'external' => true],
  'sku_56' => ['pid' => '66', 'row' => 'XYZ ROOT', 'name' => 'XYZ 30 DAY', 'duration' => '30 Days', 'price' => 850, 'external' => true],
  'sku_57' => ['pid' => '71', 'row' => 'HAX-BLADE ANDROID', 'name' => 'HAX BLADE 1 DAY', 'duration' => '1 DaYs', 'price' => 120, 'external' => true],
  'sku_58' => ['pid' => '71', 'row' => 'HAX-BLADE ANDROID', 'name' => 'HAX BLADE 10 DAY', 'duration' => '10 DaYs', 'price' => 300, 'external' => true],
  'sku_59' => ['pid' => '71', 'row' => 'HAX-BLADE ANDROID', 'name' => 'HAX BLADE 20 DAY', 'duration' => '20 DaYs', 'price' => 550, 'external' => true],
  'sku_60' => ['pid' => '71', 'row' => 'HAX-BLADE ANDROID', 'name' => 'HAX BLADE 30 DAY', 'duration' => '30 DaYs', 'price' => 850, 'external' => true],
  'sku_61' => ['pid' => '72', 'row' => 'HIKARI MOD ANDROID', 'name' => 'HIKARI 1 DAY', 'duration' => '1 Days', 'price' => 120, 'external' => true],
  'sku_62' => ['pid' => '72', 'row' => 'HIKARI MOD ANDROID', 'name' => 'HIKARI 3 DAY', 'duration' => '3 Days', 'price' => 200, 'external' => true],
  'sku_63' => ['pid' => '72', 'row' => 'HIKARI MOD ANDROID', 'name' => 'HIKARI 7 DAY', 'duration' => '7 Days', 'price' => 350, 'external' => true],
  'sku_64' => ['pid' => '72', 'row' => 'HIKARI MOD ANDROID', 'name' => 'HIKARI 30 DAY', 'duration' => '30 Days', 'price' => 850, 'external' => true],
  'sku_65' => ['pid' => '74', 'row' => 'KOS MOD ANDROID', 'name' => 'KOS MOD 1 DAY', 'duration' => '1 DaYs', 'price' => 160, 'external' => true],
  'sku_66' => ['pid' => '74', 'row' => 'KOS MOD ANDROID', 'name' => 'KOS MOD 7 DAY', 'duration' => '7 DaYs', 'price' => 550, 'external' => true],
  'sku_67' => ['pid' => '74', 'row' => 'KOS MOD ANDROID', 'name' => 'KOS MOD 30 DAY', 'duration' => '30 DaYs', 'price' => 1550, 'external' => true],
  'sku_68' => ['pid' => '69', 'row' => 'IOS MIGUL', 'name' => 'Gbox Clarification', 'duration' => 'Gbox Clarification', 'price' => 1500, 'external' => true],
  'sku_69' => ['pid' => '69', 'row' => 'IOS MIGUL', 'name' => 'MIGUL IOS BASIC 1 DAY', 'duration' => '1 DaYs Basic', 'price' => 400, 'external' => true],
  'sku_70' => ['pid' => '69', 'row' => 'IOS MIGUL', 'name' => 'MIGUL IOS BASIC 7 DAY', 'duration' => '7 DaYs Basic', 'price' => 900, 'external' => true],
  'sku_71' => ['pid' => '69', 'row' => 'IOS MIGUL', 'name' => 'MIGUL IOS BASIC 30 DAY', 'duration' => '30 DaYs Basic', 'price' => 1800, 'external' => true],
  'sku_72' => ['pid' => '69', 'row' => 'IOS MIGUL', 'name' => 'MIGUL IOS PRO 1 DAY', 'duration' => '1 DaYs PRO', 'price' => 550, 'external' => true],
  'sku_73' => ['pid' => '69', 'row' => 'IOS MIGUL', 'name' => 'MIGUL IOS PRO 7 DAY', 'duration' => '7 DaYs PRO', 'price' => 1550, 'external' => true],
  'sku_74' => ['pid' => '69', 'row' => 'IOS MIGUL', 'name' => 'MIGUL IOS 30 PRO DAY', 'duration' => '30 DaYs PRO', 'price' => 3200, 'external' => true],
  'sku_75' => ['pid' => '70', 'row' => 'NEO STRIKE ANDROID', 'name' => 'NEO STRIKE 1 DAY', 'duration' => '1 DaYs', 'price' => 120, 'external' => true],
  'sku_76' => ['pid' => '70', 'row' => 'NEO STRIKE ANDROID', 'name' => 'NEO STRIKE 3 DAY', 'duration' => '3 DaYs', 'price' => 300, 'external' => true],
  'sku_77' => ['pid' => '70', 'row' => 'NEO STRIKE ANDROID', 'name' => 'NEO STRIKE 7 DAY', 'duration' => '7 DaYs', 'price' => 500, 'external' => true],
  'sku_78' => ['pid' => '70', 'row' => 'NEO STRIKE ANDROID', 'name' => 'NEO STRIKE 14 DAY', 'duration' => '14 DaYs', 'price' => 650, 'external' => true],
  'sku_79' => ['pid' => '70', 'row' => 'NEO STRIKE ANDROID', 'name' => 'NEO STRIKE 28 DAY', 'duration' => '28 DaYs', 'price' => 850, 'external' => true],
];

function catalog_find(string $sku): ?array {
  return CATALOG[$sku] ?? null;
}

